version: '3'
services:
  nginx:
    image: nginx:1.13.6
    volumes:
      - ./:/var/www/html
      - ./docker/server/log/:/var/html/log
      - ./docker/config/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    links:
      - php
    networks:
      self:
        ipv4_address: 172.73.255.2
  php:
    build:
      context: docker/build/php
    user: 1000:1000
    links:
      - mysql
    volumes:
      - ./:/var/www/html
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      self:
        ipv4_address: 172.73.255.3
  mysql:
    image: mysql:5.7.20
    environment:
      MYSQL_USER: symfony-mosparks
      MYSQL_PASSWORD: symfony-mosparks
      MYSQL_DATABASE: symfony-mosparks
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/server/mysql:/var/lib/mysql
    networks:
      self:
        ipv4_address: 172.73.255.4
networks:
  self:
    driver: bridge
    ipam:
      config:
      - subnet: 172.73.255.0/24
